### ISSUE TITLE
Raw HTML on FB

### ISSUE THREAD

**Issue by jidanni** [NETivism/netiCRM#24]
https://www.facebook.com/neticrm/about 見到
![13440-0](https://user-images.githubusercontent.com/1230959/94935580-d0bab280-04ff-11eb-8fc3-da58cc4093f0.jpg)
又 raw HTML, 上邊又已有
```
ADDITIONAL CONTACT INFO
https://neticrm.tw/
```
故可免。

**Comment by jimyhuang** [comment]
Hello,

非常感謝回報，我們已修正此問題了。
