### ISSUE TITLE
Payment and Billing - Neweb daily sync should contain single contribution.

### ISSUE THREAD

**Issue by junsuwhy** [NETivism/netiCRM#39]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Contribution, Payment Method

### 💬 Feature description

Here are daily sync behavior for Neweb payment processor, but only for recurring contributions. Should take it effective for single contribution.

### 🚩 Redmine Issue Number

30941

**Comment by jimyhuang** [comment]
The sync button should also doing jobs like this:
- If one-time contribution have recurring id, should also change recurring status when first-time payment success
- If recurring contribution have sync button, should also fetch latest payment record from payment processor when there is new payment there(but not in crm)
