### ISSUE TITLE
Payment and Billing - Do not allow in-app browser when donation

### ISSUE THREAD

**Issue by junsuwhy** [NETivism/netiCRM#45]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 🏷️ Feature Request Type

Contribution

### 💬 Feature description

Because many problem has been occurred in in-app browser. The contribution page should recognized current browser is in-app or not.

### ✨  Solution

Recognizing current browser. If it's in-app browser, redirect the user to the default browser of his device.

### 🚩 Redmine Issue Number

29822

**Comment by jimyhuang** [comment]
This feature plan to add additional steps for users which already have good experience on in-app browser. That effect a lots of users and may effect donations. 

Move this issue out of milestone to see if we have better design for in-app browser users.
