### ISSUE TITLE
Add Content Security Policy (CSP) support

### ISSUE THREAD

**Issue by Hipfox** [NETivism/netiCRM#72]
### ⚠️ Please verify that this feature request has NOT been suggested before.

- [X] I checked and didn't find similar feature request

### 💬 Feature description

The public website page is expected to support content security policy to detect and mitigate certain types of attacks.

### ✨  Solution

Possible objectives

* Add CSP setup functionality to CRM
* Pre-defined out-of-the-box rules and the possibility for users to modify/restore the default values and exclude paths themselves.
* Generate pages to output HEADER according to CSP settings

### 🖼️ Screenshot or Simple Wireframe

none.

### 🚩 Redmine Issue Number

36952

**Comment by Hipfox** [comment]
We added a common CSP default value of `default-src 'self'; img-src 'self' data: https:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googletagmanager.com https://*.google-analytics.com https://*.facebook.net https://*.facebook.com https://*.twitter.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; font-src 'self' https://fonts.googleapis.com https://fonts.gstatic.com; frame-src 'self' https://*.facebook.net https://*.facebook.com https://*.twitter.com https://*.youtube.com https://*.vimeo.com; object-src 'none'` 
You can also override CSP in misc settings (/civicrm/admin/setting/misc) and set the exclusion path and whether to disable the CSP feature.

Please let us know if this default value is causing interference or problems.

**Comment by jimyhuang** [comment]
Do rules above cause any errors?

**Comment by Hipfox** [comment]
The answer is no, they don't. Once I have more information, I would be happy to provide a more helpful response.

**Comment by jimyhuang** [comment]
I've tested above rule. Seems work perfectly. 

Please consider change the default value to prevent effect users when deploy:
- Do not apply default value when leave blank
- Add a JS link to paste default value into textarea(We have string like this: Use default: %1)
- When install new site, save the default rule you provide to this config.

**Comment by junsuwhy** [comment]
I think it's OK that the above default value just apply to this REPO.

**Comment by Hipfox** [comment]
I would like to know how to store the default values in the settings field of the form so that they can be used after a fresh installation of CRM?

**Comment by jimyhuang** [comment]
@Hipfox, help test and finalize this function in develop branch. Thanks.
